# noqa: E501
TRAINING_DATA = [

    # =========================
    # GREETING
    # =========================

    ("hi", "greeting"),
    ("hey", "greeting"),
    ("hello", "greeting"),
    ("hii", "greeting"),
    ("hiii", "greeting"),
    ("heyy", "greeting"),
    ("heyyy", "greeting"),
    ("heyyyy", "greeting"),
    ("hey there", "greeting"),
    ("hello there", "greeting"),
    ("hi there", "greeting"),
    ("yo", "greeting"),
    ("yo there", "greeting"),
    ("sup", "greeting"),
    ("what's up", "greeting"),
    ("hey buddy", "greeting"),
    ("hello buddy", "greeting"),
    ("hi buddy", "greeting"),
    ("hello again", "greeting"),
    ("hi again", "greeting"),
    ("hey again", "greeting"),
    ("good morning", "greeting"),
    ("good afternoon", "greeting"),
    ("good evening", "greeting"),
    ("good morning ClimaBot", "greeting"),
    ("good afternoon ClimaBot", "greeting"),
    ("hello ClimaBot", "greeting"),
    ("hey ClimaBot", "greeting"),
    ("hi ClimaBot", "greeting"),
    ("hey there ClimaBot", "greeting"),
    ("namaste", "greeting"),
    ("namaste ClimaBot", "greeting"),
    ("how are you", "greeting"),
    ("how are you doing", "greeting"),
    ("how's it going", "greeting"),
    ("how are things", "greeting"),
    ("nice to meet you", "greeting"),
    ("good to meet you", "greeting"),
    ("good to see you", "greeting"),
    ("hope you're doing well", "greeting"),
    ("glad to see you", "greeting"),
    ("nice seeing you", "greeting"),
    ("hello friend", "greeting"),
    ("hi friend", "greeting"),


    # =========================
    # WEATHER
    # Current / general conditions
    # =========================

    ("how is it outside", "weather"),
    ("what's it like outdoors", "weather"),
    ("what's it like outside", "weather"),
    ("how does it look outside", "weather"),
    ("tell me the current conditions", "weather"),
    ("what are the conditions right now", "weather"),
    ("what are the conditions outside", "weather"),
    ("give me the current conditions", "weather"),
    ("give me the current weather", "weather"),
    ("tell me the current weather", "weather"),
    ("what is the weather looking like", "weather"),
    ("what does the weather look like", "weather"),
    ("how is the weather", "weather"),
    ("how's the weather", "weather"),
    ("what is the weather", "weather"),
    ("what's the weather", "weather"),
    ("tell me the weather", "weather"),
    ("give me the weather", "weather"),
    ("how is the weather outside", "weather"),
    ("what is the weather like", "weather"),
    ("what's the weather like", "weather"),
    ("is it pleasant outside", "weather"),
    ("is it nice outside", "weather"),
    ("how is the day outside", "weather"),
    ("what's happening with the weather", "weather"),
    ("tell me about the weather", "weather"),
    ("tell me about the atmosphere today", "weather"),
    ("what are things like outside", "weather"),
    ("what is it like outside right now", "weather"),
    ("what is the temperature", "weather"),
    ("what's the temperature", "weather"),
    ("what temperature is it", "weather"),
    ("how hot is it", "weather"),
    ("how cold is it", "weather"),
    ("is it hot outside", "weather"),
    ("is it cold outside", "weather"),
    ("is it warm outside", "weather"),
    ("is it cool outside", "weather"),
    ("tell me today's weather", "weather"),
    ("what's today's weather", "weather"),
    ("what is today's weather", "weather"),
    ("how is the weather today", "weather"),
    ("give me today's weather", "weather"),
    ("what's the weather like today", "weather"),
    ("weather for today", "weather"),
    ("what is weather today", "weather"),
    ("current weather please", "weather"),
    ("what is the weather in Mumbai", "weather"),
    ("weather in Mumbai", "weather"),
    ("weather in Delhi", "weather"),
    ("weather in Ahmedabad", "weather"),
    ("weather in London", "weather"),
    ("weather in Pune", "weather"),
    ("weather in Bengaluru", "weather"),
    ("weather in Kolkata", "weather"),
    ("weather in Chennai", "weather"),
    ("weather in New York", "weather"),
    ("weather in Paris", "weather"),
    ("weather in Tokyo", "weather"),
    ("temperature in Mumbai", "weather"),
    ("temperature in Delhi", "weather"),
    ("temperature in Ahmedabad", "weather"),
    ("temperature in Pune", "weather"),
    ("temperature in London", "weather"),
    ("how is the weather in Ahmedabad", "weather"),
    ("how is the weather in Delhi", "weather"),
    ("how is the weather in Pune", "weather"),
    ("how's the weather in Mumbai", "weather"),
    ("how's the weather in Ahmedabad", "weather"),
    ("what's the temperature in Delhi", "weather"),
    ("how is it in Mumbai", "weather"),
    ("how is it in Delhi", "weather"),
    ("current weather in Mumbai", "weather"),
    ("current weather in Delhi", "weather"),
    ("current weather in Ahmedabad", "weather"),
    ("current temperature in Mumbai", "weather"),
    ("tell me the weather in Mumbai", "weather"),
    ("tell me the weather in Ahmedabad", "weather"),
    ("can you tell me the weather in Mumbai", "weather"),
    ("can you tell me if it is hot in Delhi", "weather"),
    ("can you tell me if it is cold in Mumbai", "weather"),
    ("weather today in Mumbai", "weather"),
    ("weather today in Delhi", "weather"),
    ("weather today in Ahmedabad", "weather"),
    ("weather batao", "weather"),
    ("aaj ka weather", "weather"),
    ("aaj weather kaisa hai", "weather"),
    ("aaj mausam kaisa hai", "weather"),
    ("mausam kaisa hai", "weather"),


    # =========================
    # HUMIDITY
    # =========================

    ("what is the humidity", "humidity"),
    ("what's the humidity", "humidity"),
    ("how humid is it", "humidity"),
    ("how humid is the weather", "humidity"),
    ("tell me the humidity", "humidity"),
    ("give me the humidity", "humidity"),
    ("what is the humidity level", "humidity"),
    ("what's the humidity level", "humidity"),
    ("how much humidity is there", "humidity"),
    ("what is the humidity outside", "humidity"),
    ("what's the current humidity", "humidity"),
    ("give me current humidity", "humidity"),
    ("check the humidity", "humidity"),
    ("can you check humidity", "humidity"),
    ("is it humid", "humidity"),
    ("is the air humid", "humidity"),
    ("how humid is Mumbai", "humidity"),
    ("how humid is Ahmedabad", "humidity"),
    ("humidity in Delhi", "humidity"),
    ("humidity in Mumbai", "humidity"),
    ("humidity in Ahmedabad", "humidity"),
    ("humidity in Pune", "humidity"),
    ("what is the humidity in Delhi", "humidity"),
    ("what is the humidity in Ahmedabad", "humidity"),
    ("what is the humidity in Mumbai", "humidity"),
    ("humidity level in Mumbai", "humidity"),
    ("humidity level in Delhi", "humidity"),
    ("how humid is Delhi", "humidity"),
    ("tell me Mumbai's humidity", "humidity"),
    ("what is Mumbai's humidity", "humidity"),
    ("is Mumbai humid today", "humidity"),
    ("is Ahmedabad humid today", "humidity"),
    ("how much moisture is in the air", "humidity"),
    ("what's the moisture level", "humidity"),
    ("how moist is the air", "humidity"),
    ("how moist is the atmosphere", "humidity"),
    ("is the atmosphere very moist", "humidity"),
    ("is the air very moist", "humidity"),
    ("does the air feel moist", "humidity"),
    ("does the air feel damp", "humidity"),
    ("is the air damp", "humidity"),
    ("does it feel muggy outside", "humidity"),
    ("will today feel muggy", "humidity"),
    ("will it feel muggy tomorrow", "humidity"),
    ("will the air feel sticky", "humidity"),
    ("will it feel sticky tomorrow", "humidity"),
    ("does it feel sticky outside", "humidity"),
    ("will it feel uncomfortable because of moisture", "humidity"),
    ("is the air dry or damp", "humidity"),
    ("will the air be moist tomorrow", "humidity"),
    ("how much moisture is there today", "humidity"),
    ("humidity batao", "humidity"),
    ("humidity kitni hai", "humidity"),
    ("aaj humidity kitni hai", "humidity"),
    ("humidity kya hai", "humidity"),


    # =========================
    # WIND
    # =========================

    ("what is the wind speed", "wind"),
    ("what's the wind speed", "wind"),
    ("how windy is it", "wind"),
    ("how windy is the weather", "wind"),
    ("tell me the wind speed", "wind"),
    ("give me the wind speed", "wind"),
    ("what is the wind like", "wind"),
    ("what's the wind like outside", "wind"),
    ("how strong is the wind", "wind"),
    ("is it windy", "wind"),
    ("is it windy today", "wind"),
    ("is there much wind", "wind"),
    ("how fast is the wind", "wind"),
    ("what speed is the wind", "wind"),
    ("wind in Mumbai", "wind"),
    ("wind in Delhi", "wind"),
    ("wind in Ahmedabad", "wind"),
    ("wind speed in Mumbai", "wind"),
    ("wind speed in Delhi", "wind"),
    ("wind speed in Ahmedabad", "wind"),
    ("how windy is Mumbai", "wind"),
    ("how windy is Delhi", "wind"),
    ("how windy is Ahmedabad", "wind"),
    ("how strong is the wind in Ahmedabad", "wind"),
    ("what is the wind speed in Delhi", "wind"),
    ("is it windy in San Francisco", "wind"),
    ("is it windy in Mumbai", "wind"),
    ("is it windy in Delhi", "wind"),
    ("tell me about the wind", "wind"),
    ("check the wind", "wind"),
    ("can you check the wind", "wind"),
    ("what's today's wind speed", "wind"),
    ("wind today", "wind"),
    ("is the wind strong", "wind"),
    ("will there be strong winds", "wind"),
    ("how strong are the gusts", "wind"),
    ("will there be strong gusts", "wind"),
    ("how powerful are the gusts", "wind"),
    ("are strong winds expected", "wind"),
    ("is the wind calm today", "wind"),
    ("how breezy is it", "wind"),
    ("will it be breezy outside", "wind"),
    ("is there much air movement", "wind"),
    ("is the air moving quickly", "wind"),
    ("is the air moving fast", "wind"),
    ("how fast is the air moving", "wind"),
    ("how much is the air moving", "wind"),
    ("is there movement in the air", "wind"),
    ("how strong is the air movement", "wind"),
    ("is the air still today", "wind"),
    ("is the air calm outside", "wind"),
    ("how fast is the air moving outside", "wind"),
    ("hawa kaisi hai", "wind"),
    ("aaj hawa kaisi hai", "wind"),
    ("hawa kitni tez hai", "wind"),
    ("hawa tez hai kya", "wind"),
    ("hawa kaise chal rahi hai", "wind"),
    ("aaj hawa tez hai", "wind"),
    ("wind kaisi hai", "wind"),
    ("hawa ka speed kya hai", "wind"),
    ("wind batao", "wind"),
    ("aaj hawa kitni tez hai", "wind"),


    # =========================
    # RAIN
    # =========================

    ("will it rain", "rain"),
    ("will it rain today", "rain"),
    ("will it rain tomorrow", "rain"),
    ("is it going to rain", "rain"),
    ("is there rain", "rain"),
    ("is it raining", "rain"),
    ("is it raining outside", "rain"),
    ("should I expect rain", "rain"),
    ("is rain expected", "rain"),
    ("are we expecting rain", "rain"),
    ("will there be rain", "rain"),
    ("is there a chance of rain", "rain"),
    ("what are the chances of rain", "rain"),
    ("could it rain today", "rain"),
    ("could it rain tomorrow", "rain"),
    ("is rain coming", "rain"),
    ("is rain likely", "rain"),
    ("how likely is rain", "rain"),
    ("will it rain in Mumbai", "rain"),
    ("will it rain in Ahmedabad", "rain"),
    ("will it rain in Delhi tomorrow", "rain"),
    ("is it raining in Mumbai", "rain"),
    ("is it raining in Delhi", "rain"),
    ("is it raining in Ahmedabad", "rain"),
    ("rain in Mumbai", "rain"),
    ("rain in Delhi", "rain"),
    ("rain in Ahmedabad", "rain"),
    ("chances of rain in Mumbai", "rain"),
    ("chances of rain in Delhi", "rain"),
    ("will it rain today in Mumbai", "rain"),
    ("will it rain today in Ahmedabad", "rain"),
    ("is it going to rain in Mumbai", "rain"),
    ("is it going to rain in Delhi", "rain"),
    ("is Mumbai going to get rain", "rain"),
    ("are showers expected", "rain"),
    ("could it drizzle today", "rain"),
    ("is precipitation likely", "rain"),
    ("will I get caught in the rain", "rain"),
    ("is there a chance I'll get wet", "rain"),
    ("will I be able to stay dry", "rain"),
    ("is rain on the way", "rain"),
    ("do I need an umbrella", "rain"),
    ("should I carry an umbrella", "rain"),
    ("will I need an umbrella", "rain"),
    ("should I take an umbrella", "rain"),
    ("is an umbrella needed", "rain"),
    ("do I need an umbrella today", "rain"),
    ("should I take something waterproof", "rain"),
    ("will I need rain protection", "rain"),
    ("do I need rain protection", "rain"),
    ("will I get wet today", "rain"),
    ("am I likely to get wet", "rain"),
    ("will I get caught outside in the rain", "rain"),
    ("can I expect showers", "rain"),
    ("are showers coming", "rain"),
    ("is there going to be a downpour", "rain"),
    ("could there be a downpour", "rain"),
    ("is drizzle expected", "rain"),
    ("will there be precipitation", "rain"),
    ("is precipitation expected", "rain"),
    ("baarish hogi", "rain"),
    ("baarish hogi kya", "rain"),
    ("aaj baarish hogi", "rain"),
    ("kal baarish hogi", "rain"),
    ("will it rain na", "rain"),
    ("baarish aayegi kya", "rain"),


    # =========================
    # FORECAST
    # Future / upcoming conditions
    # =========================

    ("what is the forecast", "forecast"),
    ("what's the forecast", "forecast"),
    ("show me the forecast", "forecast"),
    ("give me the forecast", "forecast"),
    ("tell me the forecast", "forecast"),
    ("weather forecast", "forecast"),
    ("forecast for today", "forecast"),
    ("forecast for tomorrow", "forecast"),
    ("forecast for this week", "forecast"),
    ("forecast for next week", "forecast"),
    ("what is the forecast for tomorrow", "forecast"),
    ("what's the forecast for tomorrow", "forecast"),
    ("what will the weather be like tomorrow", "forecast"),
    ("what will the weather be like next week", "forecast"),
    ("what will the weather be like on Friday", "forecast"),
    ("how will the weather be tomorrow", "forecast"),
    ("how will the weather be this weekend", "forecast"),
    ("tell me tomorrow's weather", "forecast"),
    ("tell me the weather for tomorrow", "forecast"),
    ("give me tomorrow's forecast", "forecast"),
    ("what should I expect tomorrow", "forecast"),
    ("what should I expect this weekend", "forecast"),
    ("what should I expect this week", "forecast"),
    ("what should I expect over the next few days", "forecast"),
    ("what's coming over the next few days", "forecast"),
    ("what is coming up weather wise", "forecast"),
    ("what does the coming week look like", "forecast"),
    ("what can I expect later this week", "forecast"),
    ("what can I expect over the next few days", "forecast"),
    ("what can I expect going forward", "forecast"),
    ("how will conditions change", "forecast"),
    ("how are conditions expected to change", "forecast"),
    ("how will the weather change", "forecast"),
    ("how is the weather expected to develop", "forecast"),
    ("what's likely to happen over the next few days", "forecast"),
    ("how will things look tomorrow", "forecast"),
    ("what is expected tomorrow", "forecast"),
    ("what is expected this weekend", "forecast"),
    ("what is expected this week", "forecast"),
    ("what should I prepare for this week", "forecast"),
    ("what should I prepare for tomorrow", "forecast"),
    ("show me what's coming up", "forecast"),
    ("what's coming up", "forecast"),
    ("what's coming later", "forecast"),
    ("what happens later this week", "forecast"),
    ("how will the weather look later", "forecast"),
    ("what will conditions be like tomorrow", "forecast"),
    ("what will conditions be like this weekend", "forecast"),
    ("forecast for Mumbai tomorrow", "forecast"),
    ("forecast for Ahmedabad tomorrow", "forecast"),
    ("forecast for Delhi tomorrow", "forecast"),
    ("forecast for London tomorrow", "forecast"),
    ("weather in Mumbai tomorrow", "forecast"),
    ("weather in Ahmedabad tomorrow", "forecast"),
    ("weather in Delhi tomorrow", "forecast"),
    ("weather in London tomorrow", "forecast"),
    ("weather in Mumbai on Sunday", "forecast"),
    ("weather in Delhi on Monday", "forecast"),
    ("weather in Ahmedabad on Tuesday", "forecast"),
    ("weather tomorrow in Mumbai", "forecast"),
    ("weather tomorrow in Delhi", "forecast"),
    ("tomorrow's weather in Mumbai", "forecast"),
    ("tomorrow's weather in Delhi", "forecast"),
    ("tomorrow's forecast in Mumbai", "forecast"),
    ("tomorrow's forecast in Ahmedabad", "forecast"),
    ("what is the weather forecast for Mumbai", "forecast"),
    ("weather prediction for tomorrow", "forecast"),
    ("aaj ka forecast batao", "forecast"),
    ("kal ka forecast", "forecast"),


    # =========================
    # UNKNOWN
    # =========================

    ("what is the capital of India", "unknown"),
    ("what is the capital of France", "unknown"),
    ("who invented the telephone", "unknown"),
    ("who invented the computer", "unknown"),
    ("who is the prime minister", "unknown"),
    ("who is the president", "unknown"),
    ("who won the match", "unknown"),
    ("tell me a joke", "unknown"),
    ("tell me another joke", "unknown"),
    ("tell me a story", "unknown"),
    ("write me a story", "unknown"),
    ("write me a poem", "unknown"),
    ("write me an essay", "unknown"),
    ("what is 2 plus 2", "unknown"),
    ("what is 12 times 8", "unknown"),
    ("calculate 100 times 50", "unknown"),
    ("what is the square root of 144", "unknown"),
    ("solve this math problem", "unknown"),
    ("what is Python", "unknown"),
    ("what is Java", "unknown"),
    ("what is artificial intelligence", "unknown"),
    ("explain quantum physics", "unknown"),
    ("what is the meaning of democracy", "unknown"),
    ("tell me a fact", "unknown"),
    ("help me with my homework", "unknown"),
    ("recommend a movie", "unknown"),
    ("recommend a book", "unknown"),
    ("what should I eat", "unknown"),
    ("what should I cook", "unknown"),
    ("what should I wear", "unknown"),
    ("what should I watch", "unknown"),
    ("what should I study", "unknown"),
    ("what should I buy", "unknown"),
    ("book me a hotel", "unknown"),
    ("book me a flight", "unknown"),
    ("send an email", "unknown"),
    ("write an email for me", "unknown"),
    ("translate this sentence", "unknown"),
    ("what time is it", "unknown"),
    ("how old are you", "unknown"),
    ("who are you", "unknown"),
    ("what can you do", "unknown"),
    ("thanks", "unknown"),
    ("thank you", "unknown"),
    ("thank you so much", "unknown"),
    ("goodbye", "unknown"),
    ("see you later", "unknown"),
    ("turn on the lights", "unknown"),
    ("turn off the lights", "unknown"),
    ("turn on the fan", "unknown"),
    ("turn off the fan", "unknown"),
    ("open Chrome", "unknown"),
    ("open YouTube", "unknown"),
    ("play some music", "unknown"),
    ("play a song", "unknown"),
    ("tell me about football", "unknown"),
    ("tell me about cricket", "unknown"),
    ("what is the latest news", "unknown"),
    ("what is two plus two", "unknown"),
    ("can you help me code", "unknown"),
    ("write some Python code", "unknown"),
    ("explain this code", "unknown"),
    ("what should I do today", "unknown"),
    ("where should I travel", "unknown"),
    ("recommend a restaurant", "unknown"),
]
