# Generated by Django 6.0.5 on 2026-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='intent',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
